# Official ES 8.17.0 + IK Chinese analyzer (version must match ES)
FROM elasticsearch:8.17.0

RUN elasticsearch-plugin install --batch \
    https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-8.17.0.zip
